# Generated by Django 5.2.8 on 2025-11-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_category_alter_product_options_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='nome', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
